// Vitest-only stand-in for "@prisma/client", aliased in vitest.config.ts.
//
// The real client is generated by `prisma generate` from prisma/schema.prisma,
// which requires downloading a native engine binary — unavailable in this
// sandbox and, more importantly, not something a test suite should depend on
// to run at all. This shim exists so `npm test` works identically whether or
// not `prisma generate` has been run.
//
// IMPORTANT: the enum values below are copied from prisma/schema.prisma and
// will drift if that file changes without this one being updated. This is a
// deliberate, documented tradeoff — not an oversight — but if enum tests
// start failing after a schema change, check here first.

export const Role = {
  PATIENT: "PATIENT",
  DOCTOR: "DOCTOR",
  STAFF: "STAFF",
  ADMIN: "ADMIN",
} as const;

export const AppointmentStatus = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW",
} as const;

export const PrescriptionStatus = {
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const InvoiceStatus = {
  DRAFT: "DRAFT",
  PENDING: "PENDING",
  PAID: "PAID",
  OVERDUE: "OVERDUE",
  CANCELLED: "CANCELLED",
} as const;

export const PaymentMethod = {
  CASH: "CASH",
  CARD: "CARD",
  BANK_TRANSFER: "BANK_TRANSFER",
  MOBILE_MONEY: "MOBILE_MONEY",
  INSURANCE: "INSURANCE",
} as const;

export const NotificationType = {
  APPOINTMENT: "APPOINTMENT",
  PRESCRIPTION: "PRESCRIPTION",
  BILLING: "BILLING",
  MESSAGE: "MESSAGE",
  SYSTEM: "SYSTEM",
} as const;

function toNumber(v: number | InstanceType<typeof DecimalShim>): number {
  return typeof v === "number" ? v : v.toNumber();
}

/// A minimal stand-in for Prisma.Decimal — enough arithmetic for lib/billing.ts
/// and lib/api.ts's invoice-total math, not a general decimal library.
class DecimalShim {
  private readonly value: number;

  constructor(input: number | string) {
    this.value = typeof input === "string" ? parseFloat(input) : input;
  }

  add(other: number | DecimalShim) {
    return new DecimalShim(this.value + toNumber(other));
  }
  sub(other: number | DecimalShim) {
    return new DecimalShim(this.value - toNumber(other));
  }
  mul(other: number | DecimalShim) {
    return new DecimalShim(this.value * toNumber(other));
  }
  greaterThan(other: number | DecimalShim) {
    return this.value > toNumber(other);
  }
  greaterThanOrEqualTo(other: number | DecimalShim) {
    return this.value >= toNumber(other);
  }
  toNumber() {
    return this.value;
  }
  toString() {
    return this.value.toFixed(2);
  }
}

class PrismaClientKnownRequestErrorShim extends Error {
  readonly code: string;
  readonly clientVersion: string;
  readonly meta?: Record<string, unknown>;

  constructor(message: string, opts: { code: string; clientVersion: string; meta?: Record<string, unknown> }) {
    super(message);
    this.name = "PrismaClientKnownRequestError";
    this.code = opts.code;
    this.clientVersion = opts.clientVersion;
    this.meta = opts.meta;
  }
}

export const Prisma = {
  Decimal: DecimalShim,
  PrismaClientKnownRequestError: PrismaClientKnownRequestErrorShim,
};

/// lib/prisma.ts instantiates this at module load. Tests that don't mock
/// '@/lib/prisma' (the pure-function suites) still trigger that constructor,
/// so it must succeed — it just never needs to do anything, because those
/// tests never call a method on it. Tests that exercise database-touching
/// code always mock '@/lib/prisma' directly instead of relying on this class.
export class PrismaClient {
  constructor(_?: unknown) {}
}
